### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ftognetto** [quantosapplications/riverpod_infinite_scroll#2]
- [x] Let RiverPagedBuilder handle pull to refresh functionality. (It already know how to do this with ref.refresh)
- [x] Add support for ChangeNotifierProvider 
- [ ] Add support for FutureProvider

**Comment by romaine-murray** [comment]
Hey any updates on supporting the FutureProvider?
